### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Derek317** [Klainx/Sad-Panda#1]
Error handling response: TypeError: Cannot read properties of undefined (reading 'url') at chrome-extension://pocbcdmkddobigjcmbfaindhekkkamnd/js/background.js:4:24

I cannot access to the web and after a sec this error appears

**Comment by mrxiangsu** [comment]
I had the same problem, went to look it up and I think the author wrote the wrong name for the property

**Comment by AininChase** [comment]
what do i have to fix this?

**Comment by gsxgmpkt9020** [comment]
> what do i have to fix this?

Use this instead.

[Let's panda!](https://sleazyfork.org/en/scripts/33979-let-s-panda)
https://sleazyfork.org/en/scripts/33979-let-s-panda

**Comment by thugzillaDev** [comment]
Still having this error and unable to access site.
Error handling response: TypeError: Cannot read properties of undefined (reading 'url') at chrome-extension://ljglahgpnhibmegbioljcalhddholjbk/js/background.js:4:24
